config/routes.rb
Tugas::Application.routes.draw do
  devise_for :mahasiswas

  root :to => 'mahasiswas#index'
  resources :mahasiswas 
  match "import_mahasiswa" => "mahasiswas#import", :via => :get
  match "doimport_mahasiswa" => "mahasiswas#doimport", :via => :post
  match "import_excel_mahasiswa" => "mahasiswas#import_excel", :via => :get
  match "doimport_excel_mahasiswa" => "mahasiswas#doimport_excel", :via => :post
  match "/auth/:provider/callback" => 'authentications#create'
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :mahasiswa_id, :provider, :token, :uid

  belongs_to :mahasiswa
end

app/models/mahasiswa.rb
class Mahasiswa < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :alamat, :email, :nama, :nim, :phone, :semester, :tgllahir, :tmptlahir, :ttingkat
  attr_accessible :first_name, :last_name, :username

  validates :username, :first_name, :presence => true
  # validates :email, :presence => true, :uniqueness => true,  :on => :create
  
  #for facebooklogin
  has_many :authentications, :dependent => :delete_all

  def apply_omniauth(auth)
      # In previous omniauth, 'user_info' was used in place of 'raw_info'
      self.first_name = auth['info']['first_name']
      self.last_name = auth['info']['last_name']
      self.nama = auth['info']['name']
      self.email = auth['extra']['raw_info']['email']
      self.username = auth['info']['nickname']
      self.password = auth['info']['name']
      # Again, saving token is optional. If you haven't created the column in authentications table, this will fail
      authentications.build(:provider => auth['provider'], :uid => auth['uid'], :token => auth['credentials']['token'])
  end
  #---------------------------------------

  def self.csv_header 
  	"Nim,Nama,Semester,Tingkat,Email,Phone,Alamat,Tgllahir,Tmptlahir".split(',') 
  end 

  def self.build_from_csv(row) 
  # find existing customer from email or create new 
  cust = find_or_initialize_by_email(row[4]) 
  cust.attributes ={:nim => row[0], 
  	:nama => row[1], 
  	:semester => row[2], 
  	:ttingkat => row[3], 
  	:email => row[4], 
  	:phone => row[5], 
  	:alamat => row[6], 
  	:tgllahir => row[7],
  	:tmptlahir => row[8]} 
  	return cust 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController

	def create
	  auth = request.env["omniauth.auth"]
	  # Try to find authentication first
	  authentication = Authentication.find_by_provider_and_uid(auth['provider'], auth['uid'])
 
  	if authentication
	    # Authentication found, sign the user in.
	    flash[:notice] = "Signed in successfully."
	    sign_in_and_redirect(:mahasiswa, authentication.mahasiswa)
  	else
    	# Authentication not found, thus a new user.
    	@mahasiswa = Mahasiswa.new
    	@mahasiswa.apply_omniauth(auth)
    	if @mahasiswa.save(:validate => false)
    		MahasiswaMailer.welcome_email(@mahasiswa).deliver
	      flash[:notice] = "Account created and signed in successfully."
	      sign_in_and_redirect(:mahasiswa, @mahasiswa)
    	else
	      flash[:error] = "Error while creating a mahasiswa account. Please try again."
	      redirect_to root_url
    	end
  	end
	end 

end

app/controllers/mahasiswas_controller.rb
class MahasiswasController < ApplicationController
	before_filter :authenticate_mahasiswa!, :only => [:new, :create, :edit, :update, :destroy]
	def index
		@mahasiswas = Mahasiswa.page(params[:page]).per(10)
	end

	def show
		@mahasiswa = Mahasiswa.find(params[:id])
	end

	def new
		@mahasiswa = Mahasiswa.new
	end

	def edit
		@mahasiswa = Mahasiswa.find(params[:id])
	end

	def import
		@mahasiswa = Mahasiswa.new
	end

	def doimport
		if request.post? && params[:file].present? 
			infile = params[:file].read 
			n, errs = 0, [] 

			CSV.parse(infile) do |row| 
				n += 1 
		# SKP: header i.e. first row OR blank row 
		next if n == 1 or row.join.blank? 
		# build_from_csv method will map customer attributes & 
		# build new customer record 
		mahasiswa = Mahasiswa.build_from_csv(row) 
		# Save upon valid 
		# otherwise collect error records to export 
		if mahasiswa.valid? 
			mahasiswa.save 
		else errs << row 
		end 
		end 
		# Export Error file for later upload upon correction 
		if errs.any? 
			errFile ="errors_#{Date.today.strftime('%d%b%y')}.csv" 
			errs.insert(0, Mahasiswa.csv_header) 
			errCSV = CSV.generate do |csv| 
				errs.each {|row| csv << row} 
			end 
			send_data errCSV, 
			:type => 'text/csv; charset=iso-8859-1; header=present', 
			:disposition => "attachment; filename=#{errFile}.csv" 
		else 
			flash[:notice] = 'mahasiswa.import.success' 
			redirect_to mahasiswas_path
		end 
	end
end
	
	def import_excel
		
	end

	def doimport_excel
		# require 'spreadsheet'
		Spreadsheet.client_encoding = 'UTF-8'
		book = Spreadsheet.open params[:dump][:excel_file].tempfile
		sheet1 = book.worksheet 0
		sheet1.each do |row|
		# you can do any interesing thing with row
		mahasiswa = Mahasiswa.build_from_csv(row)
		@sukses = mahasiswa.save
		end
		if @sukses
			flash[:notice] = "Import Mahasiswa From Excel Successfully"
			redirect_to :action => :index
		else
			flash[:error] = "Import Mahasiswa From Excel Failed"
			redirect_to :action => :import_excel
		end
	end

	def create
		@mahasiswa = Mahasiswa.new(params[:mahasiswa])
		if @mahasiswa.save
			flash[:notice] = "Create new Mahasiswa Successfully"
			redirect_to :action => :index
		else
			flash[:error] = "Create new Mahasiswa Failed"
			render :action => :new
		end
	end

	def update
			@mahasiswa = Mahasiswa.find(params[:id])
		if @mahasiswa.update_attributes (params[:mahasiswa])
			flash[:notice] = "Update Mahasiswa Successfully"
			redirect_to :action => :index
		else
			flash[:error] = "Update Mahasiswa Failed"
			render :action => :edit
		end
	end

	def destroy
		@mahasiswa = Mahasiswa.find(params[:id])
    	if @mahasiswa.destroy
			flash[:notice] = "Delete Mahasiswa Successfully"
    	else
			flash[:error] = "Delete Mahasiswa Failed"
    	end	
    		redirect_to mahasiswas_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/mahasiswas_helper.rb
module MahasiswasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tugas</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="page-header"><h2>Tugas Ruby On Rails</h2>
<% if mahasiswa_signed_in? %>
Selamat Datang, <%=current_mahasiswa.username%>
<%=link_to 'Logout', destroy_mahasiswa_session_path, :method => 'delete' %>
<% end %> </div>

<%= yield %>

</body>
</html>

app/views/mahasiswas/edit.html.erb
<div id='wrapper'>
<% if flash[:error] %>
  <p class="alert-error"><%= flash[:error] %></p>
<% end %>
<h3>Edit Data <%= @mahasiswa.nama %></h3>
<%= form_for :mahasiswa,:url => mahasiswa_path(@mahasiswa.id), :html => {:method => :put} do |form| %>
<div id='content'>
<table>
<tr>
	<td>NIM:</td>
	<td><%= form.text_field :nim, :size=>60, :value=>@mahasiswa.nim %></td>
</tr>
<tr>
	<td>Nama:</td>
	<td><%= form.text_field :nama, :size=>60, :value=>@mahasiswa.nama %></td>
</tr>
<tr>
	<td>Semester:</td>
	<td><%= form.text_field :semester, :size=>4, :value=>@mahasiswa.semester %></td>
</tr>
<tr>
	<td>Tingkat:</td>
	<td><%= form.text_field :ttingkat, :size=>4, :value=>@mahasiswa.ttingkat %></td>
</tr>
<tr>
	<td>Email:</td>
	<td><%= form.text_field :email, :size=>60, :value=>@mahasiswa.email %></td>
</tr>
<tr>
	<td>Phone:</td>
	<td><%= form.text_field :phone, :size=>60, :value=>@mahasiswa.phone %></td>
</tr>
<tr>
	<td valign="top">Alamat:</td>
	<td><%= form.text_area :alamat, :rows=>3, :cols=>15, :value=>@mahasiswa.alamat %></td>
</tr>
<tr>
	<td>Tempat Lahir:</td>
	<td><%= form.text_field :tmptlahir, :size=>60, :value=>@mahasiswa.tmptlahir %></td>
</tr>
<tr>
	<td>Tanggal Lahir:</td>
	<td><%= form.text_field :tgllahir, :size=>30, :value=>@mahasiswa.tgllahir %></td>
</tr>
<tr>
	<td colspan='2'>
		<%= submit_tag "Save" %>
	</td>
</tr>
</table>
</div>
<% end %>

<%= link_to '<<Back', mahasiswas_path %>
</div>

app/views/mahasiswas/import.html.erb
<h2>Import Mahasiswa</h2>

<%= form_tag doimport_mahasiswa_path, :multipart => true do %>
  <%= file_field_tag :file %>
  <br/>
  <%= submit_tag "Import" %>
<% end %>


app/views/mahasiswas/import_excel.html.erb
<% if flash[:error] %>
  <p class="alert-error"><%= flash[:error] %></p>
<% end %>
<h3>Import Data Mahasiswa By XLS</h3>
<%= form_for :dump, :url=>{:controller=>"mahasiswas",
:action=>"doimport_excel"}, :html => { :multipart => true } do |f| %>
Select an Excel File :
<%= f.file_field :excel_file %>
<br/>
<%= submit_tag 'Submit' %>
<% end %>

app/views/mahasiswas/index.html.erb
<div id='wrapper'>	
	<% if flash[:notice] %>
      <p class="alert-success"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:error] %>
      <p class="alert-error"><%= flash[:error] %></p>
    <% end %>
	<h3>Data Mahasiswa</h3>
	<% if mahasiswa_signed_in? %>
	<div id='new'><%= link_to 'Create', new_mahasiswa_path %> OR 
	<%= link_to 'Import Form CSV', import_mahasiswa_path %> OR 
	<%= link_to 'Import Form XLS', import_excel_mahasiswa_path %></div>
	<% end %>
<div id='main'>
	<table class="table table-striped table-hover" align="center">
		<thead>
		<tr>
			<th>No</th>
			<th>NIM</th>
			<th>Nama</th>
			<th>Semester</th>
			<th>Email</th>
			<th>Action</th>
		</tr>
		</thead>
		<tbody>
		<% 
		i = 1
		@mahasiswas.each do |mahasiswa|
		%>
		<tr>
			<td><%= i %></td>
			<td><%= mahasiswa.nim %></td>
			<td><%= mahasiswa.nama %></td>
			<td><%= mahasiswa.semester %></td>
			<td><%= mahasiswa.email %></td>
			<td><%= link_to 'Detail', mahasiswa_path(mahasiswa.id) %>
				<% if mahasiswa_signed_in? %> 
			 	| <%= link_to 'Edit', edit_mahasiswa_path(mahasiswa.id) %> 
				|	<%= link_to 'Hapus', mahasiswa_path(mahasiswa.id), :method=>'delete', data: { confirm: "Kamu yakin menghapus data ini?" } %>
				<% end %></td>
		</tr>
		<%
		i += 1
		end %>
		</tbody>
	</table>
	<div id='paginate'><%=paginate @mahasiswas %></div>
</div>

app/views/mahasiswas/new.html.erb
<div id='wrapper'>
<% if flash[:error] %>
  <p class="alert-error"><%= flash[:error] %></p>
<% end %>
<h3>Tambah Data Mahasiswa</h3>
<%= form_for :mahasiswa,:url => {:action => :create} do |form| %>
<div id='content'>
<table>
<tr>
	<td>NIM:</td>
	<td><%= form.text_field :nim, :size=>60 %></td>
</tr>
<tr>
	<td>Nama:</td>
	<td><%= form.text_field :nama, :size=>60 %></td>
</tr>
<tr>
	<td>Semester:</td>
	<td><%= form.text_field :semester, :size=>4 %></td>
</tr>
<tr>
	<td>Tingkat:</td>
	<td><%= form.text_field :ttingkat, :size=>4 %></td>
</tr>
<tr>
	<td>Email:</td>
	<td><%= form.text_field :email, :size=>60 %></td>
</tr>
<tr>
	<td>Phone:</td>
	<td><%= form.text_field :phone, :size=>60 %></td>
</tr>
<tr>
	<td valign="top">Alamat:</td>
	<td><%= form.text_area :alamat, :rows=>3, :cols=>15 %></td>
</tr>
<tr>
	<td>Tempat Lahir:</td>
	<td><%= form.text_field :tmptlahir, :size=>60 %></td>
</tr>
<tr>
	<td>Tanggal Lahir:</td>
	<td><%= form.text_field :tgllahir, :size=>30 %></td>
</tr>
<tr>
	<td colspan='2'>
		<%= submit_tag "Save" %>
	</td>
</tr>
</table>
</div>
<% end %>

<%= link_to '<<Back', mahasiswas_path %>
</div>

app/views/mahasiswas/show.html.erb
<div id='wrapper'>
<h3 align="center">Data Detail <%= @mahasiswa.nama %></h3>
<div id='content'>
<table class="table table-hover" style="width:80%" align="center">
	<tr>
		<th>NIM:</th>
		<td><%= @mahasiswa.nim %></td>
	</tr>
	<tr>
		<th>Firstname:</th>
		<td><%= @mahasiswa.first_name %></td>
	</tr>
	<tr>
		<th>Lastname:</th>
		<td><%= @mahasiswa.last_name %></td>
	</tr>
	<tr>
		<th>Nama:</th>
		<td><%= @mahasiswa.nama %></td>
	</tr>
	<tr>
		<th>Username:</th>
		<td><%= @mahasiswa.username %></td>
	</tr>
	<tr>
		<th>Semester:</th>
		<td><%= @mahasiswa.semester %></td>
	</tr>
	<tr>
		<th>Tingkat:</th>
		<td><%= @mahasiswa.ttingkat %></td>
	</tr>
	<tr>
		<th>Email:</th>
		<td><%= @mahasiswa.email %></td>
	</tr>
	<tr>
		<th>Phone:</th>
		<td><%= @mahasiswa.phone %></td>
	</tr>
	<tr>
		<th>Alamat:</th>
		<td><%= @mahasiswa.alamat %></td>
	</tr>
	<tr>
		<th>Tempat Tanggal Lahir:</th>
		<td><%=  @mahasiswa.tmptlahir %>,<%= @mahasiswa.tgllahir %></td>
	</tr>
	
</table>

</div>

<%= link_to '<<Back', mahasiswas_path %>
</div>